/**
 * -------- CENTRALIZED SERVICE ERROR CODES --------
 *   This file contains all the error codes that can be thrown by the service layer.
 */

export const SERVICE_ERROR_STATUS = {
  /** General Error Codes */
  SERVICE_INPUT_INVALID: 400,
  ROLE_CONSTRAINT_VIOLATION: 422,
  OPERATION_NOT_ALLOWED: 422,
  OPERATION_FAILED: 500,
  INSUFFICIENT_PERMISSIONS: 403,

  /** Admin Error Codes */
  ADMIN_NOT_FOUND: 404,
  ADMIN_USER_CREATION_FAILED: 500,

  /** User Error Codes */
  USER_ALREADY_REGISTERED: 409,
  USER_ALREADY_PROVISIONED: 409,
  USER_NOT_PROVISIONED: 404,
  USER_NOT_FOUND: 404,
  USER_INACTIVE: 403,

  /** Society Error Codes */
  SOCIETY_NOT_FOUND: 404,
  SOCIETY_CREATION_FAILED: 500,
  SOCIETY_ALREADY_BOOTSTRAPPED: 409,

  /** Invitation Error Codes */
  INVITATION_FAILED: 500,
  INVITATION_ALREADY_EXISTS: 409,

  /** Apartment Error Codes */
  APARTMENT_SCOPE_INVALID: 400,
  DUPLICATE_APARTMENT_FOUND: 409,
  APARTMENT_NOT_FOUND: 404,

  /** Visitor Error Codes */
  VISITOR_NOT_FOUND: 404,
  VISITOR_NOT_BELONGS_TO_APARTMENT: 403,
  VISITOR_NOT_BELONGS_TO_SOCIETY: 403,
  VISITOR_NOT_BELONGS_TO_RESIDENT: 403,
  INVALID_VISITOR_APPROVAL_TRANSITION: 422,

  /** Complaint Error Codes */
  COMPLAINT_NOT_FOUND: 404,
  INVALID_COMPLAINT_STATUS_TRANSITION: 422,
} as const;

export type ServiceErrorCode =
  keyof typeof SERVICE_ERROR_STATUS;