export const CONTROLLER_ERROR_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
} as const;

export type ControllerErrorCode =
  keyof typeof CONTROLLER_ERROR_STATUS;
